//
//  ProductListInterfaces.swift
//  Saal
//
//  Created by Mozhgan
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Combine

protocol ProductListWireframeInterface: WireframeInterface {
    func routeTo(desination :ProductListViewController.Desination)
}

protocol ProductListPresenterInterface: PresenterInterface {
}
protocol ProductListDataStore {
    var storageContext : StorageContext { get set }
    
    init(storageContext : StorageContext) 
}

protocol ProductListInteractorInterface: InteractorInterface,ProductListDataStore {
    func delete(id: String)
    func search(keyword: String) -> AnyPublisher<[Product],Never>
    func fetch() -> AnyPublisher<[Product],Never>
    func findBy(id: String) -> AnyPublisher<Product,Never>
}
