//
//  SuggestibleProductsInteractor.swift
//  Saal
//
//  Created by Mozhgan on 8/11/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class SuggestibleProductsInteractor : SuggestibleProductsInteractorInterface {

    var products: [Product]
    
    init(products: [Product]) {
        self.products = products
    }
    
    func getSelectedProducts(with indexes: [Int]) -> [Product] {
        self.products.indices.filter({indexes.contains($0)}).map({self.products[$0]})
    }
}
