//
//  SuggestibleProductsWireframe.swift
//  Saal
//
//  Created by Mozhgan on 8/11/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SuggestibleProductsWireframe: BaseWireframe<SuggestibleProductsViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init(products: [Product],delegate : SuggestibleProductsWireframeMoudleDelegate) {
        let moduleViewController = SuggestibleProductsViewController()
        super.init(viewController: moduleViewController)
        let interactor = SuggestibleProductsInteractor(products: products)
        let presenter = SuggestibleProductsPresenter(interactor: interactor,
                                                     wireframe: self,
                                                     delegate: delegate)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension SuggestibleProductsWireframe: SuggestibleProductsWireframeInterface {
    func dismissSuggestibleProducts() {
        self.viewController.dismiss(animated: true)
    }
    
}
