//
//  AddOrUpdateProductInteractor.swift
//  Saal
//
//  Created by Mozhgan
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RealmSwift
import Combine

final class ProductInteractor {
    var product: AnyPublisher<Product?, Never> {
        productSubject.eraseToAnyPublisher()
    }
    var categories: AnyPublisher<[Category], Never> {
        return categorySubject.eraseToAnyPublisher()
    }
    
    private var productSubject : CurrentValueSubject<Product?,Never>
    private var categorySubject : CurrentValueSubject<[Category],Never>
    let storageContext : StorageContext
    init(storageContext : StorageContext,product : Product?) {
        self.storageContext = storageContext
        productSubject = .init(product)
        categorySubject = .init([])
        loadCategory()
    }
    
    private func loadCategory() {
        let categories =  self.storageContext.fetch(Category.self,
                                                          predicate: nil,
                                                          sorted: .init(key: "\(Category.Key.id.rawValue)"))
        categorySubject.send(Array(categories))
    }
}

// MARK: - Extensions -

extension ProductInteractor: ProductInteractorInterface {
    func deleteRelation(id: String) {
        guard let product = self.productSubject.value?.detached(),
              let index = product.relations.firstIndex(where: {$0.id == id}) else {
            return
        }
        product.relations.remove(at: index)
        self.storageContext.save(object: product)
        productSubject.send(product)
    }
    
    func addProduct(id: String,
                    name: String,
                    description: String?,
                    categoryId: String,
                    relations: [String]?) {
        let category = categorySubject.value.first(where: {$0.id == categoryId})!.detached()
        let predicate = NSPredicate(format: "id IN $ID_LIST")
        let products = storageContext.fetch(Product.self, predicate: predicate.withSubstitutionVariables(["ID_LIST": relations ?? []]), sorted: nil)
        let product = Product.init(id: id, name: name, productDescription: description)
        product.relations.append(objectsIn: Array(products))
        category.products.append(product)
        storageContext.save(object: category)
        
    }
    
    func getSuggestibleProducts() -> AnyPublisher<[Product], Never> {
        var predicate :NSPredicate?
        if let product = self.productSubject.value {
            let ids : [String] = product.relations.map({$0.id})
            predicate = .init(format: "id != $id and not(id IN $ID_LIST)")
                .withSubstitutionVariables(["id" : product.id,
                                            "ID_LIST" : ids])
        }
        let suggestibleProducts = storageContext.fetch(Product.self, predicate: predicate, sorted: .init(key: "name"))
        return Just(Array(suggestibleProducts)).eraseToAnyPublisher()
    }
    
    func addRelations(products: [Product]) {
        guard let product = self.productSubject.value?.detached() else { return  }
        product.relations.append(objectsIn: products)
        storageContext.save(object: product)
        productSubject.send(product)
        
    }
}
